# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-09 06:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstore',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2017, 11, 9)),
        ),
    ]
